# name: Run Python Script

# on:
#   schedule:
    
#     - cron: '0 * * * *'
 
#   workflow_dispatch:
#   push:
#     branches:
#       - main

# jobs:
#   run-script:
#     runs-on: ubuntu-latest
    
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3
      
#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.9' 
      
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install requests
      
#       - name: Run script
#         run: python demo.py
       
name: Run Python Script

on:
  schedule:
    - cron: '0 * * * *'  # Runs at the start of every hour
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Run script
        run: python demo.py
      
      - name: List directory contents
        run: |
          ls -alh
      
      - name: Display contents of the file (if it exists)
        run: |
          if [ -f your_file_name.txt ]; then
            echo "Contents of your_file_name.txt:"
            cat your_file_name.txt
          else
            echo "your_file_name.txt does not exist."
          fi
