# name: Run Python Script

# on:
#   schedule:
    
#     - cron: '0 * * * *'
 
#   workflow_dispatch:
#   push:
#     branches:
#       - main

# jobs:
#   run-script:
#     runs-on: ubuntu-latest
    
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3
      
#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.9' 
      
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install requests
      
#       - name: Run script
#         run: python demo.py
       
# name: Run Python Script

# on:
#   schedule:
#     - cron: '0 * * * *'  
#   workflow_dispatch:
#   push:
#     branches:
#       - main

# jobs:
#   run-script:
#     runs-on: ubuntu-latest
    
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3
      
#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.9'
      
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install requests
      
#       - name: Restore sent_timestamps.json
#         uses: actions/download-artifact@v3
#         with:
#           name: sent-timestamps
#           path: .
      
#       - name: Run script
#         run: python demo.py
       
#       - name: Save sent_timestamps.json as artifact
#         uses: actions/upload-artifact@v3
#         with:
#           name: sent-timestamps
#           path: sent_timestamps.json
name: Run Python Script

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install requests

      - name: List directory contents
        run: |
          source venv/bin/activate
          ls -alh
          
      - name: Display contents of sent_timestamps.json (if it exists)
        run: |
          source venv/bin/activate
          if [ -f sent_timestamps.json ]; then
            echo "Contents of sent_timestamps.json:"
            cat sent_timestamps.json
          else
            echo "sent_timestamps.json does not exist."
          fi
      
      - name: Run script
        run: |
          source venv/bin/activate
          python demo.py
